config/routes.rb
Ngendi::Application.routes.draw do
	root :to => "places#home"
	match "home" => "places#home"
	match "result" => "places#result"
	resources :places
 	resources :users do 
    resource :profile
 	end
 	resource :session
 	resources :categories
 	resources :tags
 	match '/login' => "sessions#new", :as => "login"
 	match '/logout' => "sessions#destroy", :as => "logout"
 	

end

app/models/place.rb
class Place < ActiveRecord::Base
  has_attached_file :photo, :styles => { :small => "200x150>", :thumb => "100x100>" },
							:url => "/assets/places/:id/:style/:basename.:extension",
							:path => ":rails_root/public/assets/places/:id/:style/:basename.:extension"
  acts_as_taggable

  acts_as_mappable	:default_units => :kms,
							:default_formula => :sphere,
							:distance_field_name => :distance,
							:lat_column_name => :latitude,
							:lng_column_name => :longitude

  validates :title, :presence => true
  validates :desc, :presence => true
  validates :address, :presence => true
  validates :phone, :presence => true
  validates :latitude, :presence => true
  validates :longitude, :presence => true
  validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']

  belongs_to :user
  belongs_to :category

  define_index do
    indexes tags.name, :as => :tags
    indexes category.name, :as => :category
    indexes :desc
    indexes :title
    indexes :address
    
    set_property :field_weight => {
      :category => 10,
      :title => 6,
      :tags => 4,
      :desc => 2,
      :address => 1
    }

    has "RADIANS(latitude)",  :as => :latitude,  :type => :float
    has "RADIANS(longitude)", :as => :longitude, :type => :float
  end

  scope :published, where("places.published_at IS NOT NULL")
  scope :draft, where("places.published_at IS NULL")
  scope :recent, lambda { published.where("place.published_at > ?", 1.week.ago.to_date) }
  scope :where_title, lambda { |term| where("places.title LIKE ?", "%#(term)%") }

  def long_title
    "#{title} - #{phone}"
  end

  def published?
    published_at.present?
  end

  def owned_by? (owner)
    return false unless owner.is_a? User
    user == owner
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_filter :authenticate, :except => [:show, :result, :home ]
  # GET /places
  # GET /places.xml
  def index
    @tags = Place.tag_counts
    @places = Place.find(:all)
    respond_to do |format|
      format.html { render :layout => "admin" }  # index.html.erb
      format.xml  { render :xml => @places }
    end
  end

  def home
    respond_to do |format|
      format.html { render :layout => "home" }  # home.html.erb
    end
  end

  #show search results page
  def result
    session[:lat] = params[:lat]
    session[:lng] = params[:lng]
    @lat = Float(params[:lat])
    @lng = Float(params[:lng])
    lat = (@lat / 180.0) * Math::PI
    lng = (@lng / 180.0) * Math::PI

    @places = Place.search params[:search], :page => params[:page], :per_page => 5, :match_mode => :boolean, :geo => [lat,lng], :with => {"@geodist" => 0.0..7_000.0}, :order => "@geodist ASC, @relevance DESC"

    respond_to do |format|
      format.html { render :layout => "result" } # result.html.erb
      format.xml  { render :xml => @places }
    end
  end

  #get tags
  def tag
    @places = Place.find_tagged_with params[:id]
  end

  # GET /places/1
  # GET /places/1.xml
  def show
    @place = Place.find(params[:id])

    respond_to do |format|
      format.html { render :layout => "show" } # show.html.erb
      format.xml  { render :xml => @place }
    end
  end

  # GET /places/new
  # GET /places/new.xml
  def new
    @place = Place.new
    respond_to do |format|
      format.html { render :layout => "admin" } # new.html.erb
      format.xml  { render :xml => @place }
    end
  end

  # GET /places/1/edit
  def edit
    if admin? 
      @place = Place.find(params[:id])
    else
      @place = current_user.places.find(params[:id])
    end
    respond_to do |format|
      format.html { render :layout => "admin" }  # index.html.erb
      format.xml  { render :xml => @place }
    end
  end

  # POST /places
  # POST /places.xml
  def create
    @place = current_user.places.new(params[:place])

    respond_to do |format|
      if @place.save
        p = Place.find(:first)
        p.tag_list = params[:place][:tag_list]
        p.save

        format.html { redirect_to(@place, :notice => 'Place was successfully created.') }
        format.xml  { render :xml => @place, :status => :created, :location => @place }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @place.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /places/1
  # PUT /places/1.xml
  def update
    @place = current_user.places.find(params[:id])

    respond_to do |format|
      if @place.update_attributes(params[:place])
        format.html { redirect_to(@place, :notice => 'Place was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @place.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.xml
  def destroy
    @place = current_user.places.find(params[:id])
    @place.destroy

    respond_to do |format|
      format.html { redirect_to(places_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_for @place, :html => { :multipart => true } do |f| %>
<% if @place.errors.any? %>
<div class="msg msg-error">
	<strong><%= pluralize(@place.errors.count, "error") %> prohibited this place from being saved:</strong>
	<ul>
		<% @place.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %> <!-- Form -->
<div class="form">
	<p>
		<%= f.label "Place Name" %>
		<%= f.text_field :title, :class => 'field size1' %>
	</p>
	<p>
		<%= f.label "Category" %>
		<%= f.collection_select :category_id, Category.find(:all), :id, :name %>
	</p>
	<p>
		<%= f.label "Tags" %>
		<%= f.text_field :tag_list, :size => 200, :class => 'field size1' %>
	</p>
	<p>
		<%= f.label "Description" %>
		<%= f.text_area :desc, :class => 'field size1' %>
	</p>
	<p>
		<%= f.label "Address" %>
		<%= f.text_field :address, :class => 'field size1' %>
	</p>
	<p>
		<%= f.label "Phone" %>
		<%= f.text_field :phone, :class => 'field size4' %>
	</p>
	<p>
		<%= f.label "Map" %> <div id="map_canvas" style="width: 500px; height: 300px;margin-left:175px;"></div>
	</p>
	<p>
		<%= f.label "Coordinate" %>
		<%= f.text_field :latitude, :class => 'field size4' %> <%= f.text_field :longitude, :class => 'field size4' %>
	</p>
	<p>
		<%= f.label "Photo" %>
		<%= f.file_field :photo %>
		<%= image_tag @place.photo.url(:thumb) %>
	</p>
</div>
<!-- End Form -->
<!-- Form Buttons -->
<div class="buttons">
	<%= link_to 'Back', places_path %> &nbsp;
	<%= f.submit  %>
</div>
<!-- End Form Buttons -->
<% end %>

app/views/places/edit.html.erb
<!-- Container -->
<div id="container">
        <div class="shell">
                <!-- Main -->
                <div id="main">
                        <div class="cl">&nbsp;</div>

                        <!-- Content -->
                        <div id="content">
                        <!-- Box -->
                            <div class="box">
                            <!-- Box Head -->
                            <div class="box-head">
                            <h2>Edit Place</h2>
                            </div>
                            <!-- End Box Head -->

<%= render 'form' %>

</div>
                        </div>
                        <!-- End Content -->
                        <div class="cl">&nbsp;</div>
                </div>
                <!-- Main -->
        </div>
</div>
<!-- End Container -->

app/views/places/home.html.erb
<div class="logo">
<%= image_tag('ngendi.png', :alt => 'Ngendi, Yogyakarta City Directory')  %>
</div>

app/views/places/index.html.erb
<!-- Container -->
<div id="container">
	<div class="shell">
		<!-- Main -->
		<div id="main">
			<div class="cl">
				&nbsp;
			</div>
			<!-- Content -->
			<div id="content">
				<!-- Box -->
				<div class="box">
					<!-- Box Head -->
					<div class="box-head">
						<h2 class="left">Places</h2>
						<div class="right">
							<label>search</label>
							<input type="text" class="field small-field" />
							<input type="submit" class="button" value="search" />
						</div>
					</div>
					<!-- End Box Head -->
					<!-- Table -->
					<div class="table">
						<table width="100%" border="0" cellspacing="0" cellpadding="0">
							<tr>
								<th>Place Name</th>
								<th>Address</th>
								<th>Category</th>
								<th width="110" class="ac">Content Control</th>
							</tr>
							<% @places.each do |place| %>
							<% if place.owned_by? current_user or admin? %>
							<tr>
								<td><h3><%= place.title %></h3></td>
								<td><%= place.address %></td>
								<td> <% if place.category %>
								<%= place.category.name %>
								<% end	%> </td>
								<td>
								<%= link_to 'Edit', edit_place_path(place), :class =>'ico edit' %>   <%= link_to 'Destroy', place, :class => 'ico del', :confirm => 'Are you sure?', :method => :$delete %> 
								</td>
							</tr>
							<% end %>
							<% end %>
						</table>
						<!-- Pagging -->
						<div class="pagging">
							<div class="left">
								Showing 1-12 of 44
							</div>
							<div class="right">
								<a href="#">Previous</a>
								<a href="#">1</a>
								<a href="#">2</a>
								<a href="#">3</a>
								<a href="#">4</a>
								<a href="#">245</a>
								<span>...</span>
								<a href="#">Next</a>
								<%= link_to 'New Place', new_place_path %>
							</div>
						</div>
						<!-- End Pagging -->
					</div>
					<!-- Table -->
				</div>
				<!-- End Box -->
			</div>
			<!-- End Content -->
			<div class="cl">
				&nbsp;
			</div>
		</div>
		<!-- Main -->
	</div>
</div>
<!-- End Container -->

app/views/places/new.html.erb
<!-- Container -->
<div id="container">
	<div class="shell">
		<!-- Main -->
		<div id="main">
			<div class="cl">
				&nbsp;
			</div>
			<!-- Content -->
			<div id="content">
				<!-- Box -->
				<div class="box">
					<!-- Box Head -->
					<div class="box-head">
						<h2>Add New Place</h2>
					</div>
					<!-- End Box Head -->
					<%= render 'form' %>
				</div>
			</div>
			<!-- End Content -->
			<div class="cl">
				&nbsp;
			</div>
		</div>
		<!-- Main -->
	</div>
</div>
<!-- End Container -->

app/views/places/result.html.erb
<div id="content">
<ul>
<span class="info">
<% if !@places.blank? %>
<div style="padding:3px 0 3px 5px;">
<small>Page <%= @places.current_page %> of <%= @places.total_pages %> ( <%= @places.total_entries %> results ) </small>
</div>
<% @places.each do |place| %>
</span>
	<li>
	  <a class="noeffect" href="<%= place_path(place)  %>"><span class="image" style="background-image: url('<%= place.photo.url(:thumb) %>');"></span>
	  <span class="comment"><% if place.category %>
    	  <%= place.category.name %>
    	  <% end	%></span>
		<span class="name"><%= place.title %> </span>
		<span class="starcomment"><%= place.address %></span>
		<span class="arrow"></span>
		<span class="price">&plusmn; <%= sprintf("%.2f", place.sphinx_attributes['@geodist']/1000+1) %> km </span>
		</a>
	</li>
<% end %>
<% else %>
<div style="text-align:center;margin-top:30px;">
<strong>Nasi Mana Nasi</strong>
</div>
<% end  %>
</ul>
</div>

<%= will_paginate @places, :class => 'pagination' %>

app/views/places/show.html.erb
<p id="notice">
	<%= notice %>
</p>
<span class="graytitle"><%= @place.title %></span>
<ul class="pageitem">
	<li class="textbox">
		<div id="map_canvas" style="height: 300px;"></div>
	</li>
</ul>
<ul class="pageitem">
	<li class="textbox">
		<div id="directionsPanel"></div>
	</li>
</ul>
<ul id="info" class="pageitem">
	<li class="textbox">
		<p>
			<%= @place.desc %>
		</p>
	</li>
</ul>
<ul class="pageitem">
	<li class="textbox">
		Alamat : <%= @place.address %>
	</li>
	<li class="textbox">
		Telpon : <%= @place.phone %>
	</li>
	<li class="textbox">
		<center>
			<%= image_tag @place.photo.url(:small) %>
		</center>
	</li>
</ul>
<center>
	<a href="<%= root_path %>">
	<input type="button" value="Home" />
	</a>
	<% if logged_in? %> <a href="<%= places_path %>">
	<input type="button" value="Dashboard" />
	</a>
	<% end  %>
</center>