config/routes.rb
Ngendi::Application.routes.draw do
	root :to => "places#home"
	match "home" => "places#home"
	match "result" => "places#result"
	resources :places
 	resources :users do 
    resource :profile
 	end
 	resource :session
 	resources :categories
 	resources :tags
 	match '/login' => "sessions#new", :as => "login"
 	match '/logout' => "sessions#destroy", :as => "logout"
 	

end

app/views/layouts/admin.html.erb
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1">
		<title>Ngendi</title>
		<%= stylesheet_link_tag("style-admin") %>
		<%= javascript_include_tag :all %>
		<%= csrf_meta_tag %> <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAQiyrUtXN3XgjBRs0Im0c5RTU4okvaG2eWWHakbncH7s9-PHQlxSRE2LHPblyFYKNecQlbLPMttP7oQ" type="text/javascript"></script>
	</head>
	<body onload="initialize()" onunload="GUnload()">
		<!-- Header -->
		<div id="header">
			<div class="shell">
				<!-- Logo + Top Nav -->
				<div id="top">
					<h1><%= link_to 'Dashboard - Ngendi', places_path %></h1>
					<div id="top-navigation">
						<%= current_user.email %> <span> | </span>
						<%= link_to "View Ngendi", root_path %> <span> | </span>
						<%= link_to "Edit Password", edit_user_path(current_user) %> <span> | </span>
						<%= link_to "Logout", logout_path %>
					</div>
				</div>
				<!-- End Logo + Top Nav -->
				<!-- Main Nav -->
				<div id="navigation">
					<ul>
						<li>
							<%= link_to content_tag(:span, "Places"), places_path %>
						</li>
						<li>
							<%= link_to content_tag(:span, "Categories"), categories_path %>
						</li>
						<% if admin? %>
						<li>
							<%= link_to content_tag(:span, "Contributors"), users_path %>
						</li>
						<% end %>
					</ul>
				</div>
				<!-- End Main Nav -->
			</div>
		</div>
		<!-- End Header -->
		<div class="msg msg-ok">
			<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
			<%= content_tag :p, alert, :class => 'alert' if alert.present? %>
		</div>
		<%= yield %> <!-- Footer -->
		<div id="footer">
			<div class="shell">
				<span class="left">&copy; 2011 - Ngendi</span>
				<span class="right"> Design by <a href="http://chocotemplates.com" target="_blank" title="The Sweetest CSS Templates WorldWide">Chocotemplates.com</a> </span>
			</div>
		</div>
		<!-- End Footer -->
		</div>
	</body>
</html>

app/views/layouts/application.html.erb
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" /> 
	<meta id="viewport" name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" /> 
  <title>Ngendi</title>
  <%= stylesheet_link_tag("style") %>
  <%= javascript_include_tag :all %>
  <%= csrf_meta_tag %>
  <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAQiyrUtXN3XgjBRs0Im0c5RTU4okvaG2eWWHakbncH7s9-PHQlxSRE2LHPblyFYKNecQlbLPMttP7oQ" type="text/javascript"></script> 
  
</head>

<body onload="initialize()" onunload="GUnload()"> 
<div id="wrapper">

<div id="topbar" class="transparent">
	<div id="title">Ngendi</div>
	<div id="leftnav">
	<%= link_to "Back", root_path, :id => 'backButton' %>
	</div>
</div>

<div id="searchbox">
<%= form_tag result_path, :method => :get do %>
	<fieldset>
	<%= text_field_tag :search, params[:search], :placeholder => 'search' %> 
	<%= hidden_field_tag :lat, params[:lat] %>
	<%= hidden_field_tag :lng, params[:lng] %>
	<%= submit_tag "Cari", :name => nil %>
	</fieldset>
<% end %>
</div>

<div id="content">
<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
<%= content_tag :p, alert, :class => 'alert' if alert.present? %>
<%= yield %>
</div>

<div id="footer">
<p>Development of Ngendi.com</p>
</div>
</div>
</body>
</html>

app/views/layouts/home.html.erb
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>
  <meta http-equiv="content-type" content="text/html; charset=utf-8" /> 
  <meta id="viewport" name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" /> 
  <title>Ngendi</title>
  <meta name="description" content="Yogyakarta City Directory" />
  <%= stylesheet_link_tag("style") %>
  <%= javascript_include_tag "geo",:cache => true %>
  <%= javascript_include_tag "functions",:cache => true %>
  <%= csrf_meta_tag %>
  
</head>

<body onload="initialize()" onunload="GUnload()"> 
<div id="wrapper">

<div id="topbar" class="transparent">
	<div id="title">Ngendi</div>
</div>

<script type="text/javascript"> 
		if(geo_position_js.init()){
			geo_position_js.getCurrentPosition(success_callback,error_callback,{enableHighAccuracy:true});
		}
		else{
			alert("Functionality not available");
		}
 
		function success_callback(p)
		{
			document.getElementById("lat").value=p.coords.latitude.toFixed(17);
			document.getElementById("lng").value=p.coords.longitude.toFixed(17);
		}		
		function error_callback(p)
		{
			alert('error='+p.code);
		}	
</script> 

<div class="searchbox">
<%= form_tag result_path, :method => :get do %>
      <fieldset>
      <%= text_field_tag :search, nil, :placeholder => 'search' %>
      <%= hidden_field_tag :lat %>
      <%= hidden_field_tag :lng %>
      <%= submit_tag "Cari", :name => nil, :id => :submit, :type => :hidden %>
      </fieldset>
<% end %>
</div>

<div id="content">
<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
<%= content_tag :p, alert, :class => 'alert' if alert.present? %>
<%= yield %>
</div>

<div id="footer">
<p>Development of Ngendi.com</p>
</div>
</div>
</body>
</html>

app/views/layouts/login.html.erb
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1">
		<title>Ngendi</title>
		<%= stylesheet_link_tag("style-admin") %>
	</head>
	<body>
		<!-- Header -->
		<div id="header">
			<div class="shell">
				<!-- Logo + Top Nav -->
				<div id="top">
					<h1><%= link_to 'Ngendi', root_path %></h1>
				</div>
				<!-- End Logo + Top Nav -->
			</div>
		</div>
		<!-- End Header -->
		<div class="msg msg-ok">
			<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
			<%= content_tag :p, alert, :class => 'alert' if alert.present? %>
		</div>
		<%= yield %> <!-- Footer -->
		<div id="footer">
			<div class="shell">
				<span class="left">&copy; 2010 - Ngendi</span>
				<span class="right"> Design by <a href="http://chocotemplates.com" target="_blank" title="The Sweetest CSS Templates WorldWide">Chocotemplates.com</a> </span>
			</div>
		</div>
		<!-- End Footer -->
		</div>
	</body>
</html>

app/views/layouts/result.html.erb
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<meta id="viewport" name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
		<title>Ngendi <%= params[:search] %></title>
		<%= stylesheet_link_tag("style") %>
		<%= javascript_include_tag "functions", :cache => true %>
		<%= csrf_meta_tag %> <script src="http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAQiyrUtXN3XgjBRs0Im0c5RTU4okvaG2eWWHakbncH7s9-PHQlxSRE2LHPblyFYKNecQlbLPMttP7oQ" type="text/javascript"></script>
	</head>
	<body onload="initialize()" onunload="GUnload()" class="applist">
		<div id="wrapper">
			<div id="topbar" class="transparent">
				<div id="title">
					Ngendi
				</div>
				<div id="leftnav">
					<%= link_to "Back", root_path, :id => 'backButton' %>
				</div>
			</div>
			<div class="searchbox">
				<%= form_tag result_path, :method => :get do %>
				<fieldset>
					<%= text_field_tag :search, params[:search], :placeholder => 'search' %>
					<%= hidden_field_tag :lat, params[:lat] %>
					<%= hidden_field_tag :lng, params[:lng] %>
					<%= submit_tag "Cari", :name => nil, :type => :hidden %>
				</fieldset>
				<% end %>
			</div>
			<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
			<%= content_tag :p, alert, :class => 'alert' if alert.present? %>
			<%= yield %>
			<div id="footer">
				<p>
					Development of Ngendi.com
				</p>
			</div>
		</div>
	</body>
</html>

app/views/layouts/show.html.erb
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"> 
<head>
  <meta charset="utf-8"> 
	<meta name="viewport" content="width=device-width, minimum-scale=1, maximum-scale=1"> 
  <title><%= @place.title %> - Ngendi</title>
  <%= stylesheet_link_tag("style") %>
  <%= javascript_include_tag "google_maps", :cache => true %>
  <%= javascript_include_tag "functions", :cache => true %>
  <%= csrf_meta_tag %>
  <%= javascript_include_tag("http://maps.google.co.id/maps/api/js?v=3&key=ABQIAAAAQiyrUtXN3XgjBRs0Im0c5RTU4okvaG2eWWHakbncH7s9-PHQlxSRE2LHPblyFYKNecQlbLPMttP7oQ&region=ID&language=ID&sensor=false") %>  
   
<% javascript_tag do %>
  var directionDisplay;
  var directionsService = new google.maps.DirectionsService();
  var map;
 
  function initialize() {
    directionsDisplay = new google.maps.DirectionsRenderer();
    var jogja = new google.maps.LatLng(<%= session[:lat] %>, <%= session[:lng] %>);
    var myOptions = {
      zoom:14,
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      center: jogja
    }
    map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
    directionsDisplay.setMap(map);
    directionsDisplay.setPanel(document.getElementById("directionsPanel"));
  }
  
  function calcRoute() {
    var start = "<%= session[:lat] %>, <%= session[:lng] %>";
    var end = "<%= @place.latitude %>, <%= @place.longitude %>";
    var request = {
        origin:start, 
        destination:end,
        travelMode: google.maps.DirectionsTravelMode.DRIVING
    };
    directionsService.route(request, function(response, status) {
      if (status == google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(response);
      }
    });
  }
<% end  %> 
</head>
<body onload="initialize();calcRoute();" onunload="GUnload()"> 
<div id="topbar" class="transparent">
	<div id="title">Ngendi</div>
	<div id="leftnav"> 
		<a href="<%= root_path %>"><img alt="home" src="../images/home.png" /></a></div>
</div>

<div class="searchbox">
<%= form_tag result_path, :method => :get do %>
	<fieldset>
	<%= text_field_tag :search, nil, :placeholder => 'search' %> 
	<%= hidden_field_tag :lat, session[:lat] %>
	<%= hidden_field_tag :lng, session[:lng] %>
	<%= submit_tag "Cari", :name => nil, :type => :hidden %>
	</fieldset>
<% end %>
</div>

<div id="tributton"> 
	<div class="links"> 
		<a href="#map_canvas">Map</a><a href="#directionsPanel">Direction</a><a href="#info">Info</a></div> 
</div> 

<div id="content">
<%= content_tag :p, notice, :class => 'notice' if notice.present? %>
<%= content_tag :p, alert, :class => 'alert' if alert.present? %>
<%= yield %>
</div>

<div id="footer">
<p><strong>Development of Ngendi.com</strong></p>
</div>
</body>
</html>